### ISSUE TITLE
Make it more generic

### ISSUE THREAD

**Issue by rturgano** [bcgov/Gov-2.0-Bootstrap-Skeleton#1]
Anybody want to help make the code more generic? Right now, you can see some Ministry of Environment references.

**Comment by juhewitt** [comment]
I opened this one up again, as I had a read through of the custom-main.css and saw some env declarations.  Can you tell me what those refer to @rturgano?

**Comment by Gavin-McLeod** [comment]
Had a quick look and did some text searches through custom-main.css, and the Master and x-Col sampler HTML files.

It looks like the env- styles are not used that widely and that a simple refactoring of the CSS file and samplers should do the trick.

Master.html makes calls to css/env-main.css and css/env-form.css, which don't exist.  I suspect these have been renamed to custom-main and custom-form.  Otherwise, very little use is made of the env- named classes in the samplers so I would like to propose:

1. search and replace "**env-**" with "**gov2-**" in the custom-main.css file, then
2. do the same in the samplers.
3. rewrite the calls for the env-custom and env-form in Master.html

I don't mind trying this in a separate environment, testing and submitting the changes as a PR.  Can't promise a delivery time though ;)  Can anyone think of any gotchas before I give this a go?

**Comment by juhewitt** [comment]
I would say for your second bullet, just replace with "gov-" in the custom-main.  All sounds good to me.  Yes, a Pull Request and then submit would be great.

**Comment by Gavin-McLeod** [comment]
Unable to push a branch in order to create the PR.  Permission prob?

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin Refactor_CSS_from_ENV_to_GOV:Refactor_CSS_from_ENV_to_GOV
remote: **Permission to bcgov-c/Gov-2.0-Bootstrap-Skeleton.git denied to Gavin-McLeod.**
fatal: unable to access 'https://github.com/bcgov-c/Gov-2.0-Bootstrap-Skeleton/': The requested URL returned error: 403

**Comment by Gavin-McLeod** [comment]
Pull Request made to hopefully address this issue.

**Comment by Gavin-McLeod** [comment]
With the pull request (Refactor CSS clas names from "env-*" to "gov-*" and edit the calls in… #8) merged, can this issue be closed?

**Comment by juhewitt** [comment]
Yup, closing!
